version: '3.3'
services:
  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    volumes:
      - ipfs_data:/data/ipfs
    ports:
      - '5001:5001'
      - '8011:8011'
    networks:
      - superGraph
    restart: 'unless-stopped'
  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    volumes:
      - ceramic_daemon:/root/.ceramic
    command:
      - '--network=inmemory'
    ports:
      - '7007:7007'
    environment:
      - NODE_ENV=production
    depends_on:
      - ipfs
    networks:
      - superGraph
    restart: unless-stopped
  composedb:
    image: akashafoundation/composedb-graphql:latest
    environment:
      - NODE_ENV=production
      - CERAMIC_API_ENDPOINT=${CERAMIC_API_ENDPOINT}
      - COMPOSEDB_GRAPHQL_PORT=${COMPOSEDB_GRAPHQL_PORT}
    expose:
      - "${COMPOSEDB_GRAPHQL_PORT}"
    networks:
      - superGraph
    depends_on:
      - ceramic
    restart: unless-stopped
  indexing:
    image: akashafoundation/indexing-graphql:latest
    environment:
      - NODE_ENV=production
      - CERAMIC_API_ENDPOINT=${CERAMIC_API_ENDPOINT}
      - GRAPHQL_INDEXING_PORT=${GRAPHQL_INDEXING_PORT}
      - DID_INDEXING_PRIVATE_KEY=${DID_INDEXING_PRIVATE_KEY}
    expose:
      - "${GRAPHQL_INDEXING_PORT}"
    depends_on:
      - composedb
    networks:
      - superGraph
    restart: unless-stopped
  gateway:
    image: akashafoundation/gateway-graphql:latest
    ports:
      - "5001:${GRAPHQL_GATEWAY_PORT}"
    environment:
      - NODE_ENV=production
      - GRAPHQL_GATEWAY_PORT=${GRAPHQL_GATEWAY_PORT}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
    depends_on:
      - composedb
      - indexing
    networks:
      - superGraph
    restart: unless-stopped
networks:
  superGraph:
    driver: bridge
volumes:
  ipfs_data: {}
  ceramic_daemon: {}
