federation_version: =2.6.1
subgraphs:
  composedb:
    routing_url: ${env.COMPOSEDB_URL}
    schema:
      file: ./composedb-schema.graphql
      #subgraph_url:
  streams:
    routing_url: ${env.INDEXING_URL}
    schema:
      file: ./streams-schema.graphql
