federation_version: =2.3.2
subgraphs:
  composedb:
    routing_url: ${env.COMPOSEDB_URL}
    schema:
      file: ./composedb-schema.graphql
      #subgraph_url:
  streams:
    routing_url: ${env.STREAMS_URL}
    schema:
      file: ./streams-schema.graphql
